### ISSUE TITLE
Wrong location for Midsummer Fire Festival Bonfire 

### ISSUE THREAD

**Issue by jdc843** [Ravendwyr/HandyNotes_SummerFestival#11]
Pandaria's Krasarang Wilds  Midsummer Bonfire at 77.75, 3.54 should be changed to 74.0, 9.49 Zhu's Watch.
REF: https://www.wowhead.com/midsummer-fire-festival-guide#bonfires-pandaria
 
Great mod. Thank you for taking the time to create it.

I was unable to create a comment on curseforge for some reason.

**Comment by Ravendwyr** [comment]
This isn't the first time I've had to fix the coordinates for this fire. See #9.
What keeps changing it I wonder?
