### ISSUE TITLE
[BUG] cata midsummer

### ISSUE THREAD

**Issue by amey1956** [Ravendwyr/HandyNotes_SummerFestival#12]
**Describe the bug**
there are quest markers for outland fires but no flame icons making it a little harder to see. 

thanks ;)

**To Reproduce**
Steps to reproduce the behaviour:
2. Click on '...'
3. Scroll down to '...'

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by Ravendwyr** [comment]
I don't have a character that's a high enough level to go to Outland at the moment. Can you share a screenshot in the meantime?

**Comment by Ravendwyr** [comment]
Does this still happen in v1.8.1?

**Comment by Ravendwyr** [comment]
Gonna close this for now as no response. If the issue is ongoing, feel free to reopen.
