### ISSUE TITLE
LUA Error after logging in

### ISSUE THREAD

**Issue by KevinAllenWiegand** [Ravendwyr/HandyNotes_SummerFestival#14]
Message: Interface/AddOns/Blizzard_SharedXML/Mixin.lua:31: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun Jun 23 15:26:21 2024
Count: 3
Stack: Interface/AddOns/Blizzard_SharedXML/Mixin.lua:31: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/Mixin.lua"]:31: in function <Interface/AddOns/Blizzard_SharedXML/Mixin.lua:28>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TomCats/midsummer/TomCatsMidsummerDataProvider.lua"]:321: in function <...s/TomCats/midsummer/TomCatsMidsummerDataProvider.lua:318>
[string "@Interface/AddOns/TomCats/midsummer/TomCatsMidsummerDataProvider.lua"]:387: in function `OnAcquired'
[string "@Interface/AddOns/Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:201: in function <...ace/AddOns/Blizzard_MapCanvas/Blizzard_MapCanvas.lua:158>
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/TomCats/proxy.lua"]:32: in function `AcquirePin'
[string "@Interface/AddOns/TomCats/midsummer/TomCatsMidsummerDataProvider.lua"]:260: in function `RefreshAllData'
[string "@Interface/AddOns/TomCats/midsummer/TomCatsMidsummerDataProvider.lua"]:190: in function `?'
[string "@Interface/AddOns/TomCats/midsummer/libs/TomCatsLibs/Events.lua"]:53: in function <...AddOns/TomCats/midsummer/libs/TomCatsLibs/Events.lua:47>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by KevinAllenWiegand** [comment]
Also getting this error just clicking around the main map to different zones.

**Comment by Ravendwyr** [comment]
This is the wrong addon. Your error report is related to @TomCats Tours.
https://github.com/TomCats/TomCats-WoW-AddOns
