### ISSUE TITLE
New Cataclysm version not storing collected nodes?

### ISSUE THREAD

**Issue by dblanch369** [Ravendwyr/HandyNotes_SummerFestival#18]
**Describe the bug**
If you log out and back into the game, the fires re-appear on the maps as uncollected, even after collecting.

**To Reproduce**
Steps to reproduce the behaviour:
1. visit and interact with fires (it removes the icon from the map)
2. log out
3. log back in
4. All fires re-appear on maps, regardless of status.

**Expected behaviour**
Fires that are already done for a character during the event, should remain off the map.

**Screenshots**
None

**Additional context**
Handynotes Summer Festival v1.8.0. WoW Cataclysm 4.4.0 (55141) (Release arm64)

Thank you!

**Comment by dblanch369** [comment]
Seems to work fine in Retail however.  Only Cata version isn't remembering what I've collected.

**Comment by Ravendwyr** [comment]
I have a funny feeling I know what's happening here. I'll look at it after work this evening.

**Comment by dblanch369** [comment]
No problem! Thanks!
